### Create a new prompt
POST http://localhost:8081/api/prompts
Content-Type: application/json


{
  "title": "Test",
  "category": "TestCat",
  "text": "Das ist ein Test",
  "aiModel": "ChatGPT"
}



### Get all prompts
GET http://localhost:8081/api/prompts
